OrdererOrgs:
  - Name: Orderer
    Domain: capstone.com
    EnableNodeOUs: false
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: registrar.capstone.com
    EnableNodeOUs: false
    Template:
      Count: 6
    Users:
      Count: 1