#!/bin/bash
# ============================================================
# BLOCKGO - DEPLOYMENT RECOVERY & FIXES
# ============================================================
set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; BLUE='\033[0;34m'; NC='\033[0m'

log_info() { echo -e "${GREEN}[RECOVERY]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Determine script location
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

export PATH=$PATH:$(pwd)/bin
export FABRIC_CFG_PATH="$(pwd)/config"

log_info "========================================="
log_info "BLOCKGO Deployment Recovery Started"
log_info "========================================="

# STEP 1: Cleanup
log_info "STEP 1: Cleaning up failed containers..."
docker compose -f docker-compose-main.yaml -f docker-compose-annex.yaml -f docker-compose-pubad.yaml down -v --remove-orphans 2>/dev/null || true
sleep 2

# STEP 2: Check CA TLS certificates exist
log_info "STEP 2: Verifying CA TLS certificates..."
CA_TLS_PATHS=("./fabric-ca/registrar/tls-cert.pem" "./fabric-ca/faculty/tls-cert.pem" "./fabric-ca/department/tls-cert.pem")
CERTS_MISSING=0

for CA_TLS in "${CA_TLS_PATHS[@]}"; do
    if [ ! -f "$CA_TLS" ]; then
        log_warn "Missing: $CA_TLS"
        CERTS_MISSING=$((CERTS_MISSING + 1))
    else
        log_info "✓ Found $CA_TLS"
    fi
done

if [ $CERTS_MISSING -gt 0 ]; then
    log_error "CA TLS certificates missing ($CERTS_MISSING). These must be generated by the CA container first."
fi

# STEP 3: Start only CAs
log_info "STEP 3: Starting Fabric CAs..."
TMP_DOCKER_CFG=$(mktemp -d)
echo "{}" > "$TMP_DOCKER_CFG/config.json"
DOCKER_CONFIG=$TMP_DOCKER_CFG docker compose -f docker-compose-main.yaml -f docker-compose-annex.yaml -f docker-compose-pubad.yaml up -d ca.registrar.capstone.com ca.faculty.capstone.com ca.department.capstone.com cli
rm -rf "$TMP_DOCKER_CFG"

# STEP 4: Wait for CAs
log_info "STEP 4: Waiting for CAs to be ready..."
wait_for_ca() {
    local port=$1
    local name=$2
    local timeout=120
    local start_time=$(date +%s)
    
    log_info "Checking CA on port $port..."
    while true; do
        if docker exec cli bash -c "curl -s -k https://127.0.0.1:$port/cainfo > /dev/null 2>&1" 2>/dev/null; then
            log_info "✓ $name is ready"
            return 0
        fi
        
        if [ $(($(date +%s) - start_time)) -ge $timeout ]; then
            docker logs ca.registrar.capstone.com 2>&1 | tail -20
            log_error "$name timeout!"
        fi
        sleep 3
    done
}

wait_for_ca 7054 "Registrar CA"
wait_for_ca 8054 "Faculty CA"
wait_for_ca 9054 "Department CA"

# STEP 5: Check enrollment status
log_info "STEP 5: Checking existing enrollments..."
ENROLLMENTS_OK=true

check_enrollment() {
    local org=$1
    local domain=$2
    local msp_path="./crypto-config-final-v2/peerOrganizations/${domain}/users/Admin@${domain}/msp/signcerts"
    
    if [ -d "$msp_path" ] && [ "$(ls -A $msp_path)" ]; then
        log_info "✓ $org already enrolled"
        return 0
    else
        log_warn "⚠ $org needs re-enrollment"
        ENROLLMENTS_OK=false
        return 1
    fi
}

check_enrollment "Registrar" "registrar.capstone.com"
check_enrollment "Faculty" "faculty.capstone.com"
check_enrollment "Department" "department.capstone.com"

# STEP 6: Re-enroll if necessary
if [ "$ENROLLMENTS_OK" = false ]; then
    log_info "STEP 6: Re-enrolling organizations..."
    
    enroll_org() {
        local ORG=$1
        local DOMAIN=$2
        local PORT=$3
        local MSP_ID=$4
        local ADMIN_PASS=${BOOTSTRAP_REGISTRAR_PASS:-adminpw}
        local ORG_DIR="$(pwd)/crypto-config-final-v2/peerOrganizations/${DOMAIN}"
        local TLS_CERT="$(pwd)/fabric-ca/${ORG}/tls-cert.pem" 
        
        log_info "Enrolling ${MSP_ID}..."
        rm -rf "${ORG_DIR}" 2>/dev/null || true
        mkdir -p "${ORG_DIR}/msp" "${ORG_DIR}/users/Admin@${DOMAIN}/msp" "${ORG_DIR}/peers/peer0.${DOMAIN}/msp" "${ORG_DIR}/peers/peer0.${DOMAIN}/tls" "${ORG_DIR}/peers/peer1.${DOMAIN}/msp" "${ORG_DIR}/peers/peer1.${DOMAIN}/tls"

        # Admin enrollment
        fabric-ca-client enroll -u https://admin:${ADMIN_PASS}@127.0.0.1:${PORT} --caname ca-${ORG} --tls.certfiles "${TLS_CERT}" --home "${ORG_DIR}" || log_error "Failed to enroll admin for $ORG"
        
        # Register and enroll peer0
        fabric-ca-client register --caname ca-${ORG} --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${TLS_CERT}" --home "${ORG_DIR}" 2>/dev/null || true
        fabric-ca-client enroll -u https://peer0:peer0pw@127.0.0.1:${PORT} --caname ca-${ORG} -M "${ORG_DIR}/peers/peer0.${DOMAIN}/msp" --tls.certfiles "${TLS_CERT}" --home "${ORG_DIR}" || log_error "Failed to enroll peer0 for $ORG"
        fabric-ca-client enroll -u https://peer0:peer0pw@127.0.0.1:${PORT} --caname ca-${ORG} -M "${ORG_DIR}/peers/peer0.${DOMAIN}/tls" --enrollment.profile tls --csr.hosts "peer0.${DOMAIN},localhost" --tls.certfiles "${TLS_CERT}" --home "${ORG_DIR}" || log_error "Failed to enroll peer0 TLS for $ORG"
        
        # Normalize peer0 TLS certificates
        mkdir -p "${ORG_DIR}/peers/peer0.${DOMAIN}/tls/keystore" "${ORG_DIR}/peers/peer0.${DOMAIN}/tls/signcerts"
        cp "${ORG_DIR}/peers/peer0.${DOMAIN}/tls/signcerts/"* "${ORG_DIR}/peers/peer0.${DOMAIN}/tls/server.crt" 2>/dev/null || true
        cp "${ORG_DIR}/peers/peer0.${DOMAIN}/tls/keystore/"* "${ORG_DIR}/peers/peer0.${DOMAIN}/tls/server.key" 2>/dev/null || true
        cp "${ORG_DIR}/msp/cacerts/127.0.0.1-${PORT}-ca-${ORG}.pem" "${ORG_DIR}/peers/peer0.${DOMAIN}/tls/ca.crt" 2>/dev/null || true
        
        # Register and enroll peer1
        fabric-ca-client register --caname ca-${ORG} --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${TLS_CERT}" --home "${ORG_DIR}" 2>/dev/null || true
        fabric-ca-client enroll -u https://peer1:peer1pw@127.0.0.1:${PORT} --caname ca-${ORG} -M "${ORG_DIR}/peers/peer1.${DOMAIN}/msp" --tls.certfiles "${TLS_CERT}" --home "${ORG_DIR}" || log_error "Failed to enroll peer1 for $ORG"
        fabric-ca-client enroll -u https://peer1:peer1pw@127.0.0.1:${PORT} --caname ca-${ORG} -M "${ORG_DIR}/peers/peer1.${DOMAIN}/tls" --enrollment.profile tls --csr.hosts "peer1.${DOMAIN},localhost" --tls.certfiles "${TLS_CERT}" --home "${ORG_DIR}" || log_error "Failed to enroll peer1 TLS for $ORG"
        
        # Normalize peer1 TLS certificates
        mkdir -p "${ORG_DIR}/peers/peer1.${DOMAIN}/tls/keystore" "${ORG_DIR}/peers/peer1.${DOMAIN}/tls/signcerts"
        cp "${ORG_DIR}/peers/peer1.${DOMAIN}/tls/signcerts/"* "${ORG_DIR}/peers/peer1.${DOMAIN}/tls/server.crt" 2>/dev/null || true
        cp "${ORG_DIR}/peers/peer1.${DOMAIN}/tls/keystore/"* "${ORG_DIR}/peers/peer1.${DOMAIN}/tls/server.key" 2>/dev/null || true
        cp "${ORG_DIR}/msp/cacerts/127.0.0.1-${PORT}-ca-${ORG}.pem" "${ORG_DIR}/peers/peer1.${DOMAIN}/tls/ca.crt" 2>/dev/null || true
        
        # Register and enroll admin
        fabric-ca-client register --caname ca-${ORG} --id.name orgadmin --id.secret adminpw --id.type admin --tls.certfiles "${TLS_CERT}" --home "${ORG_DIR}" 2>/dev/null || true
        fabric-ca-client enroll -u https://orgadmin:adminpw@127.0.0.1:${PORT} --caname ca-${ORG} -M "${ORG_DIR}/users/Admin@${DOMAIN}/msp" --tls.certfiles "${TLS_CERT}" --home "${ORG_DIR}" || log_error "Failed to enroll orgadmin for $ORG"
        
        # Create MSP config and TLS certs
        local CA_FILENAME="127.0.0.1-${PORT}-ca-${ORG}.pem"
        mkdir -p "${ORG_DIR}/msp/tlscacerts" "${ORG_DIR}/tlsca"
        cp "${ORG_DIR}/msp/cacerts/${CA_FILENAME}" "${ORG_DIR}/msp/tlscacerts/tlsca.${DOMAIN}-cert.pem"
        cp "${ORG_DIR}/msp/cacerts/${CA_FILENAME}" "${ORG_DIR}/tlsca/tlsca.${DOMAIN}-cert.pem"
        
        cat <<EOF > "${ORG_DIR}/msp/config.yaml"
NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/${CA_FILENAME}
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/${CA_FILENAME}
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/${CA_FILENAME}
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/${CA_FILENAME}
    OrganizationalUnitIdentifier: orderer
EOF
        cp "${ORG_DIR}/msp/config.yaml" "${ORG_DIR}/users/Admin@${DOMAIN}/msp/config.yaml"
        cp "${ORG_DIR}/msp/config.yaml" "${ORG_DIR}/peers/peer0.${DOMAIN}/msp/config.yaml"
        cp "${ORG_DIR}/msp/config.yaml" "${ORG_DIR}/peers/peer1.${DOMAIN}/msp/config.yaml"
        
        log_info "✓ ${MSP_ID} enrolled successfully"
    }
    
    enroll_org "registrar" "registrar.capstone.com" 7054 "RegistrarMSP"
    enroll_org "faculty" "faculty.capstone.com" 8054 "FacultyMSP"
    enroll_org "department" "department.capstone.com" 9054 "DepartmentMSP"
else
    log_info "STEP 6: All organizations already enrolled, skipping re-enrollment"
fi

# STEP 7: Enroll orderer
log_info "STEP 7: Checking orderer enrollment..."
ORDERER_DIR="$(pwd)/crypto-config-final-v2/ordererOrganizations/capstone.com"

if [ ! -d "$ORDERER_DIR/orderers/orderer.capstone.com/tls" ] || [ -z "$(ls -A $ORDERER_DIR/orderers/orderer.capstone.com/tls 2>/dev/null)" ]; then
    log_info "Enrolling orderers..."
    
    rm -rf "$ORDERER_DIR" 2>/dev/null || true
    mkdir -p "${ORDERER_DIR}/msp" "${ORDERER_DIR}/orderers/orderer.capstone.com/msp" "${ORDERER_DIR}/orderers/orderer.capstone.com/tls" "${ORDERER_DIR}/orderers/orderer2.capstone.com/msp" "${ORDERER_DIR}/orderers/orderer2.capstone.com/tls" "${ORDERER_DIR}/orderers/orderer3.capstone.com/msp" "${ORDERER_DIR}/orderers/orderer3.capstone.com/tls"
    
    TLS_CERT="$(pwd)/fabric-ca/registrar/tls-cert.pem"
    ADMIN_PASS=${BOOTSTRAP_REGISTRAR_PASS:-adminpw}
    PORT=7054
    
    # Orderer 1
    fabric-ca-client enroll -u https://admin:${ADMIN_PASS}@127.0.0.1:${PORT} --caname ca-registrar --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" || log_error "Failed orderer admin enroll"
    fabric-ca-client register --caname ca-registrar --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" 2>/dev/null || true
    fabric-ca-client enroll -u https://orderer:ordererpw@127.0.0.1:${PORT} --caname ca-registrar -M "${ORDERER_DIR}/orderers/orderer.capstone.com/msp" --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" || log_error "Failed orderer MSP enroll"
    fabric-ca-client enroll -u https://orderer:ordererpw@127.0.0.1:${PORT} --caname ca-registrar -M "${ORDERER_DIR}/orderers/orderer.capstone.com/tls" --enrollment.profile tls --csr.hosts "orderer.capstone.com,localhost,orderer-1.plv-main-campus.svc.cluster.local" --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" || log_error "Failed orderer TLS enroll"
    
    mkdir -p "${ORDERER_DIR}/orderers/orderer.capstone.com/tls/keystore" "${ORDERER_DIR}/orderers/orderer.capstone.com/tls/signcerts"
    cp "${ORDERER_DIR}/orderers/orderer.capstone.com/tls/signcerts/"* "${ORDERER_DIR}/orderers/orderer.capstone.com/tls/server.crt" 2>/dev/null || true
    cp "${ORDERER_DIR}/orderers/orderer.capstone.com/tls/keystore/"* "${ORDERER_DIR}/orderers/orderer.capstone.com/tls/server.key" 2>/dev/null || true
    cp "${ORDERER_DIR}/msp/cacerts/127.0.0.1-${PORT}-ca-registrar.pem" "${ORDERER_DIR}/orderers/orderer.capstone.com/tls/ca.crt" 2>/dev/null || true
    mkdir -p "${ORDERER_DIR}/orderers/orderer.capstone.com/msp/admincerts"
    cp "./crypto-config-final-v2/peerOrganizations/registrar.capstone.com/users/Admin@registrar.capstone.com/msp/signcerts/cert.pem" "${ORDERER_DIR}/orderers/orderer.capstone.com/msp/admincerts/cert.pem" 2>/dev/null || true
    
    # Orderer 2
    fabric-ca-client register --caname ca-registrar --id.name orderer2 --id.secret ordererpw --id.type orderer --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" 2>/dev/null || true
    fabric-ca-client enroll -u https://orderer2:ordererpw@127.0.0.1:${PORT} --caname ca-registrar -M "${ORDERER_DIR}/orderers/orderer2.capstone.com/msp" --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" || true
    fabric-ca-client enroll -u https://orderer2:ordererpw@127.0.0.1:${PORT} --caname ca-registrar -M "${ORDERER_DIR}/orderers/orderer2.capstone.com/tls" --enrollment.profile tls --csr.hosts "orderer2.capstone.com,localhost,orderer-2.plv-main-campus.svc.cluster.local" --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" || true
    
    mkdir -p "${ORDERER_DIR}/orderers/orderer2.capstone.com/tls/keystore" "${ORDERER_DIR}/orderers/orderer2.capstone.com/tls/signcerts"
    cp "${ORDERER_DIR}/orderers/orderer2.capstone.com/tls/signcerts/"* "${ORDERER_DIR}/orderers/orderer2.capstone.com/tls/server.crt" 2>/dev/null || true
    cp "${ORDERER_DIR}/orderers/orderer2.capstone.com/tls/keystore/"* "${ORDERER_DIR}/orderers/orderer2.capstone.com/tls/server.key" 2>/dev/null || true
    cp "${ORDERER_DIR}/msp/cacerts/127.0.0.1-${PORT}-ca-registrar.pem" "${ORDERER_DIR}/orderers/orderer2.capstone.com/tls/ca.crt" 2>/dev/null || true
    mkdir -p "${ORDERER_DIR}/orderers/orderer2.capstone.com/msp/admincerts"
    cp "./crypto-config-final-v2/peerOrganizations/registrar.capstone.com/users/Admin@registrar.capstone.com/msp/signcerts/cert.pem" "${ORDERER_DIR}/orderers/orderer2.capstone.com/msp/admincerts/cert.pem" 2>/dev/null || true
    
    # Orderer 3
    fabric-ca-client register --caname ca-registrar --id.name orderer3 --id.secret ordererpw --id.type orderer --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" 2>/dev/null || true
    fabric-ca-client enroll -u https://orderer3:ordererpw@127.0.0.1:${PORT} --caname ca-registrar -M "${ORDERER_DIR}/orderers/orderer3.capstone.com/msp" --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" || true
    fabric-ca-client enroll -u https://orderer3:ordererpw@127.0.0.1:${PORT} --caname ca-registrar -M "${ORDERER_DIR}/orderers/orderer3.capstone.com/tls" --enrollment.profile tls --csr.hosts "orderer3.capstone.com,localhost,orderer-3.plv-annex-campus.svc.cluster.local" --tls.certfiles "${TLS_CERT}" --home "${ORDERER_DIR}" || true
    
    mkdir -p "${ORDERER_DIR}/orderers/orderer3.capstone.com/tls/keystore" "${ORDERER_DIR}/orderers/orderer3.capstone.com/tls/signcerts"
    cp "${ORDERER_DIR}/orderers/orderer3.capstone.com/tls/signcerts/"* "${ORDERER_DIR}/orderers/orderer3.capstone.com/tls/server.crt" 2>/dev/null || true
    cp "${ORDERER_DIR}/orderers/orderer3.capstone.com/tls/keystore/"* "${ORDERER_DIR}/orderers/orderer3.capstone.com/tls/server.key" 2>/dev/null || true
    cp "${ORDERER_DIR}/msp/cacerts/127.0.0.1-${PORT}-ca-registrar.pem" "${ORDERER_DIR}/orderers/orderer3.capstone.com/tls/ca.crt" 2>/dev/null || true
    mkdir -p "${ORDERER_DIR}/orderers/orderer3.capstone.com/msp/admincerts"
    cp "./crypto-config-final-v2/peerOrganizations/registrar.capstone.com/users/Admin@registrar.capstone.com/msp/signcerts/cert.pem" "${ORDERER_DIR}/orderers/orderer3.capstone.com/msp/admincerts/cert.pem" 2>/dev/null || true
    
    # Orderer MSP config
    CA_FILENAME="127.0.0.1-${PORT}-ca-registrar.pem"
    mkdir -p "${ORDERER_DIR}/msp/tlscacerts" "${ORDERER_DIR}/tlsca"
    cp "${ORDERER_DIR}/msp/cacerts/${CA_FILENAME}" "${ORDERER_DIR}/msp/tlscacerts/tlsca.capstone.com-cert.pem"
    cp "${ORDERER_DIR}/msp/cacerts/${CA_FILENAME}" "${ORDERER_DIR}/tlsca/tlsca.capstone.com-cert.pem"
    
    cat <<EOF > "${ORDERER_DIR}/msp/config.yaml"
NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/${CA_FILENAME}
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/${CA_FILENAME}
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/${CA_FILENAME}
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/${CA_FILENAME}
    OrganizationalUnitIdentifier: orderer
EOF
    cp "${ORDERER_DIR}/msp/config.yaml" "${ORDERER_DIR}/orderers/orderer.capstone.com/msp/config.yaml"
    cp "${ORDERER_DIR}/msp/config.yaml" "${ORDERER_DIR}/orderers/orderer2.capstone.com/msp/config.yaml"
    cp "${ORDERER_DIR}/msp/config.yaml" "${ORDERER_DIR}/orderers/orderer3.capstone.com/msp/config.yaml"
    
    log_info "✓ Orderers enrolled successfully"
else
    log_info "STEP 7: Orderers already enrolled, skipping"
fi

# STEP 8: Generate channel artifacts
log_info "STEP 8: Generating channel artifacts..."
mkdir -p ./channel-artifacts-final

if ! configtxgen -profile UniversityGenesis -channelID system-channel -outputBlock "./channel-artifacts-final/orderer.genesis.block" 2>&1; then
    log_error "Failed to generate genesis block. Check configtx.yaml"
fi

if ! configtxgen -profile RegistrarChannel -outputBlock "./channel-artifacts-final/registrar-channel.block" -channelID registrar-channel 2>&1; then
    log_error "Failed to generate registrar-channel block"
fi

log_info "✓ Channel blocks generated"

# STEP 9: Cleanup
log_info "STEP 9: Shutting down CAs..."
docker compose -f docker-compose-main.yaml -f docker-compose-annex.yaml -f docker-compose-pubad.yaml down -v --remove-orphans 2>/dev/null || true

log_info "========================================="
log_info "✓ RECOVERY COMPLETE!"
log_info "========================================="
log_info "Next steps:"
log_info "  1. Review ./channel-artifacts-final/ exists"
log_info "  2. Run: docker compose -f docker-compose-main.yaml up -d"
log_info "  3. Then run: ./k8s/deploy-k8s.sh apply"
log_info "========================================="
